export const MOOD = [
  { e: "😞", l: "Low", c: "#F87171", v: 0 },
  { e: "😔", l: "Meh", c: "#FB923C", v: 1 },
  { e: "😐", l: "Okay", c: "#FBBF24", v: 2 },
  { e: "🙂", l: "Good", c: "#86EFAC", v: 3 },
  { e: "😊", l: "Great", c: "#34D399", v: 4 },
];

export const TAGS = [
  "Work 💼",
  "Anxiety 😰",
  "Sleep 🌙",
  "Family 🏡",
  "Joy ✨",
  "Exercise 💪",
  "Stress 😤",
  "Gratitude 🙏",
  "Focus 🎯",
  "Relationships 💞",
];

export const PLUGINS = [
  {
    id: "breathe",
    name: "4-7-8 Breathing",
    icon: "🌬️",
    author: "@wellness_dev",
    installs: "12.4k",
    cat: "Calm",
    color: "#34D399",
    desc: "Guided breathing cycles to activate your parasympathetic nervous system.",
    active: true,
  },
  {
    id: "cbt",
    name: "CBT Thought Record",
    icon: "🧩",
    author: "@therapy_tools",
    installs: "8.1k",
    cat: "Therapy",
    color: "#A78BFA",
    desc: "Structured cognitive distortion identification and reframing exercises.",
    active: false,
  },
  {
    id: "gratitude",
    name: "Daily Gratitude 3x3",
    icon: "🙏",
    author: "@mindful_builds",
    installs: "21k",
    cat: "Habits",
    color: "#FBBF24",
    desc: "Three gratitude prompts, three times a day. Rewires negativity bias.",
    active: true,
  },
  {
    id: "body",
    name: "Body Scan Meditation",
    icon: "🧘",
    author: "@somatic_lab",
    installs: "5.3k",
    cat: "Calm",
    color: "#60A5FA",
    desc: "Progressive body awareness meditation from head to toe.",
    active: false,
  },
  {
    id: "sleep",
    name: "Sleep Wind-Down",
    icon: "🌙",
    author: "@sleep_science",
    installs: "17.8k",
    cat: "Sleep",
    color: "#F472B6",
    desc: "30-min evening routine: dimming reflections, tomorrow prep, sleep cue.",
    active: false,
  },
  {
    id: "affirmations",
    name: "Identity Affirmations",
    icon: "⚡",
    author: "@neuro_habits",
    installs: "9.2k",
    cat: "Growth",
    color: "#F59E0B",
    desc: "Science-backed identity-based affirmation system to shift self-concept.",
    active: true,
  },
];

export const JOURNAL_ENTRIES = [
  {
    id: 1,
    mood: 3,
    text: "Had a really productive day. Pushed through that feature I've been avoiding for two weeks. The team loved the demo. Feeling genuinely accomplished — but also a little drained from it all.",
    tags: ["Work 💼", "Joy ✨"],
    date: "Today, 9:14 PM",
    insight: "Your productivity peaks correlate with completing avoided tasks. Procrastination may be your biggest energy drain.",
  },
  {
    id: 2,
    mood: 1,
    text: "Woke up with this heavy feeling that I couldn't shake. Deadlines are piling up. I snapped at my sister over dinner and immediately felt terrible about it.",
    tags: ["Anxiety 😰", "Stress 😤", "Family 🏡"],
    date: "Yesterday, 8:42 PM",
    insight: "High stress tends to spill into relationships. You might benefit from a brief decompression ritual before family time.",
  },
  {
    id: 3,
    mood: 4,
    text: "Morning run at 6am. First time in two weeks. Everything looked different in that early light. Journaled for 20 minutes after. This is what consistency feels like.",
    tags: ["Exercise 💪", "Gratitude 🙏"],
    date: "Mon, 7:31 AM",
    insight: "Your highest mood entries all include physical movement. Morning is your optimal window for exercise.",
  },
  {
    id: 4,
    mood: 2,
    text: "Nothing particularly wrong, nothing particularly right. Just... existing. Sometimes I wonder if I'm living on autopilot. What am I actually working toward?",
    tags: ["Focus 🎯"],
    date: "Sun, 11:58 PM",
    insight: "Existential questioning often precedes meaningful directional shifts. This restlessness is a signal, not a problem.",
  },
];